
version: 0.2

env:
  variables:
    ENVIRONMENT: 'dev'

#TODO this needs to know env so it can add to save location, rn conflict with prod

phases:
  build:
    commands:
      # Install AWS Cli
      # - yum install -y unzip
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - ./aws/install

      # update path to include intalled node version
      - export PATH=$PATH:/usr/local/nvm/versions/node/v14.17.4/bin

      # Install TypeScript
      - npm install -D typescript

      # Build android app
      - npm install
      - npm run build
      - npm install -g @ionic/cli
      - ionic capacitor add android

      #build android native app
      - cd android
      - /opt/gradle/gradle-7.4.2/bin/gradle build -b build.gradle

      # Copy to S3
      - echo $ENVIRONMENT
      - aws s3 cp --recursive app/build/outputs/apk/release s3://klubby-${ENVIRONMENT}-andrioid-pipeline-atifacts-bucket/build
      #  s3://klubby-deployment-ios-dev-pipelineartifactsbucket-1gw13zwjh93vj/android/$ENVIRONMENT
artifacts:
  files:
    - 'android/app/build/outputs/apk/release/**/*'
  name: 'klubby-android-deployment-dev-BuildArtifact'