
version: 0.2

env:
  variables:
    ENVIRONMENT: 'dev'

phases:
  build:
    commands:
      # Install AWS Cli
      - npm install -g unzip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      # Install TypeScript
      - npm install -D typescript
      # Build iOS app
      - npm install
      - npm run build
      - npm install -g @ionic/cli
      - ionic capacitor add ios
      # Copy to S3
      - aws s3 cp -r ios s3://klubby-deployment-ios-dev-pipelineartifactsbucket-72ae00j2dw1w/ios/