
version: 0.2

env:
  variables:
    ENVIRONMENT: 'dev'

phases:
  build:
    commands:
      - npm install -g aws-cli
      - npm install -D typescript
      - npm install
      - npm run build
      - npm install -g @ionic/cli
      - ionic capacitor add ios
      - aws s3 cp -r ios s3://klubby-deployment-ios-dev-pipelineartifactsbucket-72ae00j2dw1w/ios/